media:
  input: images
content:
  - name: blog
    label: บทความ (Blog)
    type: collection
    path: blog
    fields:
      - name: title
        label: ชื่อเรื่อง
        type: string
      - name: cover_image
        label: รูปภาพหน้าปก
        type: image
      - name: description
        label: คำเกริ่นนำ (Excerpt / SEO Description)
        type: string
      - name: tags
        label: แท็ก (Tags)
        type: select
        options:
           label: โภชนบำบัด
           value: โภชนบำบัด
           label: โภชนบริการ
           value: โภชนบริการ
      - name: pathophysiology
        label: 1. พยาธิสภาพของโรค
        type: rich-text
      - name: clinical_assessment
        label: 2. การประเมินทางคลินิก
        type: rich-text
      - name: mnt
        label: 3. โภชนบำบัดทางการแพทย์
        type: rich-text
      - name: dietary_guidelines
        label: 4. แนวทางการจัดการอาหาร
        type: rich-text
      - name: food_drug_interactions
        label: 5. ปฏิกิริยาระหว่างอาหารและยา
        type: rich-text
      - name: complication_management
        label: 6. การจัดการภาวะแทรกซ้อน
        type: rich-text
      - name: ncp
        label: 7. กระบวนการดูแลทางโภชนาการ
        type: rich-text
      - name: references
        label: แหล่งอ้างอิง (References)
        type: rich-text
      - name: FAQ
        label: คำถามที่พบบ่อย
        type: rich-text