media:
  input: images
content:
  - name: blog
    label: บทความ (Blog)
    type: collection
    path: blog
    fields:
      - name: title
        label: ชื่อเรื่อง
        type: string
      - name: body
        label: เนื้อหา
        type: rich-text