media:
  input: images
content:
  - name: blog
    label: บทความ (Blog)
    type: collection
    path: blog
    fields:
      - name: title
        label: ชื่อเรื่อง
        type: string
      - name: cover_image
        label: รูปภาพหน้าปก
        type: image
      - name: description
        label: คำเกริ่นนำ (Excerpt / SEO Description)
        type: string
      - name: body
        label: เนื้อหา
        type: rich-text
      - name: references
        label: แหล่งอ้างอิง (References)
        type: rich-text