backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "notes"
    label: "สรุปเนื้อหา (Notes)"
    folder: "blog"
    create: true
    fields:
      - {label: "หัวข้อเรื่อง (Title)", name: "title", widget: "string"}
      
      - {label: "หมวดหมู่ (Category)", name: "category", widget: "select", options: ["โภชนาการทั่วไป", "โภชนาการเด็ก", "ความรู้เรื่องโรค", "อื่นๆ"], default: "อื่นๆ"}
      
      - {label: "สีธีมของโน้ต (Theme Color)", name: "color", widget: "color", required: false}
      
      - {label: "รูปหน้าปก (Cover Image)", name: "image", widget: "image", required: false}
      
      - {label: "โน้ตย่อ / ใจความสำคัญ (Short Note)", name: "summary", widget: "text", required: false}
      
      - {label: "เนื้อหาแบบละเอียด (Body)", name: "body", widget: "markdown"}
